### ISSUE TITLE
Implement DataProviders

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/Sponge#2545]
### Tasks ###

- [ ] Check/Implement/Optimize `DataProvider`s for all `Keys`
- [ ] Javadocs on Keys match implementation?
- [ ] how to identify readonly values in API? Readonly Annotation?
- [ ] check/enforce bounded values (see below)

### by DataProviderRegistryBuilders ###
- [ ] TileEntityDataProviders
    - [ ] `COOLDOWN` Hopper 0
- [ ] LocationDataProviders
- [ ] BlockDataProviders
  - [ ] often apply to BlockTypes not just the State holding it
  - [ ] auto-register for better mod support
  - [ ] piston blocks
- [ ] CommandBlockLogicDataProviders (TileEntityDataProviders,EntityDataProviders)
- [ ] EntityDataProviders
  - [ ] Sponge<Animal>Types deduplicate code
  - [ ] support all `SHOOTER` ProjectileSource types
  - [ ] CatEntity Keys
  - [x] Fox `IS_DEFENDING`
  - [x] Panda Keys
  - [ ] `RAID_WAVE` returned Wave is mutable?
  - [x] Horse color/style
  - [ ] minecart and boat movement Keys `CAN_MOVE_ON_LAND`, `DERAILED_VELOCITY_MODIFIER`, `OCCUPIED_DECELERATION`, `POTENTIAL_MAX_SPEED`, `SWIFTNESS`, `UNOCCUPIED_DECELERATION`
  - [ ] `ATTACK_DAMAGE` for other projectiles than Arrows
  - [ ] fish base/pattern color deduplicate code
  - [ ] `BOSS_BAR` mutable? only implemented for Wither
  - [ ] some Humanoid Keys `CAN_FLY` only implemented for player
- [ ] generic package - currently registered under EntityDataProviders and ItemStackDataProviders
- [ ] InventoryDataProviders
- [ ] ItemStackDataProvider
  - [ ] often apply to ItemTypes not just the Stack holding it
  - [ ] ItemDisplayNameProvider is for ItemType not ItemStack
  - [ ] `ARMOR_TYPE` was removed? IArmorMaterial exists ItemStackArmorTypeProvider invalid
  - [ ] `FLUID_ITEM_STACK` ItemStackFluidProvider invalid
  - [ ] some Keys from BlockDataProviders may make sense on ItemStack/Type
  - [ ] providers for Spawner Keys on ItemStacks
  - [ ] `APPLICABLE_POTION_EFFECTS` setter possible?
- [ ] ItemStackDataProviders
- [ ] EntityNbtDataProviders

### not persisted ###

- [ ] `AFFECTS_SPAWNING` is not persisted
- [ ] `AIRBORNE_VELOCITY_MODIFIER` is not persisted

### bounds not enforced ###
invalid values may cause issues

- [ ] `AGE` enforce bounded value >= 0
- [ ] `ANGER_LEVEL` enforce bounded >= 0 and max short
- [ ] `GENERATION` enforce bounded value should be >= 0 (vanilla 0-3 with 3 unused)
- [ ] `BABY_TICKS` enforce bounded value should be >= 0
- [ ] PROFESSION_LEVEL - bounds? 1-4? modded could maybe allow more

### no Key? ###

- [ ] IS_TRIGGERED dispenser? `IS_POWERED`?
- [ ] IS_ENABLED hopper? `IS_POWERED`?
- [ ] BOUNDING_BOX
- [ ] SKIN_UNIQUE_ID HumanEntity? `SKIN`?
- [ ] REVENGE_TARGET Living?
- [ ] ARMOR_TYPE ItemStack/Type?
- [ ] FIREWORK_LIFETIME FireworkRocketEntity `LIFE_TICKS`?
- [ ] IS_REPAIRABLE - `ItemType`

### Keys ###
- [x] `ABSORPTION`
- [x] `ACCELERATION`
- [x] `ACTIVE_ITEM`
- [x] `AFFECTS_SPAWNING`
- [x] `AGE`
- [x] `AIRBORNE_VELOCITY_MODIFIER`
- [x] `ANGER_LEVEL`
- [x] `APPLICABLE_POTION_EFFECTS`
- [x] `APPLIED_ENCHANTMENTS`
- [x] `ART_TYPE`
- [x] `ATTACHMENT_SURFACE`
- [x] `ATTACK_DAMAGE` for arrows
- [ ] `ATTACK_DAMAGE` non-vanilla for other projectiles
- [x] `ATTACK_TIME`
- [x] `AUTHOR`
- [x] `AXIS`
- [x] `BABY_TICKS`
- [x] `BANNER_PATTERN_LAYERS`
- [x] `BASE_SIZE`
- [x] `BASE_VEHICLE`
- [x] `BEAM_TARGET_ENTITY`
- [ ] `BIOME_TEMPERATURE` location based data is not implemented!
- [x] `BLAST_RESISTANCE`
- [ ] `BLOCK_LIGHT`
- [x] `BLOCK_STATE`
- [x] `BLOCK_TEMPERATURE`
- [x] `BODY_ROTATIONS`
- [ ] `BOSS_BAR` mutable? dataholders? - only implemented for Wither
- [x] `BREAKABLE_BLOCK_TYPES` 
- [x] `BREEDER`
- [x] `BREEDING_COOLDOWN`
- [x] `BURN_TIME`
- [x] `CAN_BREED`
- [x] `CAN_DROP_AS_ITEM`
- [ ] `CAN_FLY` ?not sure about provider for humanoids
- [x] `CAN_GRIEF` implemented via GrieferBridge
- [x] `CAN_HARVEST`
- [x] `CAN_HURT_ENTITIES`
- [x] `CAN_JOIN_RAID`
- [ ] `CAN_MOVE_ON_LAND` (also for minecart?)
- [x] `CAN_PLACE_AS_BLOCK` name?
- [x] `CASTING_TIME` 
- [x] `CAT_TYPE`
- [x] `CHAT_COLORS_ENABLED` readonly
- [x] `CHAT_VISIBILITY` readonly
- [x] `CHEST_ATTACHMENT_TYPE`
- [x] `CHEST_ROTATION`
- [ ] `COLOR` lots of providers - check them all
- [x] `COMMAND`
- [x] `COMPARATOR_MODE`
- [ ] `CONNECTED_DIRECTIONS`  lots of providers - check them all
- [x] `CONTAINER_ITEM`
- [x] `COOLDOWN`
- [ ] `CREATOR` missing provider non-vanilla? javadocs
- [x] `CURRENT_SPELL`
- [ ] `CUSTOM_ATTACK_DAMAGE` missing provider non-vanilla?
- [x] `CUSTOM_NAME`
- [x] `DAMAGE_ABSORPTION`
- [x] `DAMAGE_PER_BLOCK` healing with negative values?
- [x] `DECAY_DISTANCE` 1-7
- [x] `DERAILED_VELOCITY_MODIFIER`
- [x] `DESPAWN_DELAY`
- [x] `DESTROY_SPEED`
- [x] `DETONATOR` TNT
- [ ] `DETONATOR` creeper data possible?
- [ ] `DIRECTION` lots of providers - check if all providers present - duplicate code need cleanup
- [x] `DISPLAY_NAME`
  - [x] ItemStack
  - [x] Entity
  - [x] LockableTileEntity
  - [x] Inventory (readonly - if it is a INameable or Container Viewing INameable)
- [x] `DOMINANT_HAND`
- [x] `DO_EXACT_TELEPORT`
- [x] `DURATION` 
- [ ] `DURATION_ON_USE` javadocs positive=increase
- [ ] `DYE_COLOR` lots of providers - ItemStackDyeColorProvider not implemented - sometimes readonly?
- [x] `EATING_TIME`
- [x] `EFFICIENCY`
- [x] `EGG_TIME`
- [x] `END_GATEWAY_AGE` 
- [x] `EQUIPMENT_TYPE`
- [ ] `EXHAUSTION` bounded value 0-4 wrong? missing provider for non-player javadocs wrong - exhaust max 40 on tick over 4 reduces by 4 and reduces saturation or foodlevel
- [ ] `EXPERIENCE` bounded value should be >= 0 ; negative xp on orbs does not wo<rk
- [ ] `EXPERIENCE_FROM_START_OF_LEVEL` readonly bounded value?
- [ ] `EXPERIENCE_LEVEL` bounded value should be >= 0
- [ ] `EXPERIENCE_SINCE_LEVEL` bounded value should be >= 0
- [ ] `EXPLOSION_RADIUS` bounded value should be >= 0
- [ ] `EYE_HEIGHT`
- [ ] `EYE_POSITION`
- [ ] `FALL_DISTANCE` bounded value should be >= 0
- [ ] `FALL_TIME` bounded value should be >= 0
- [ ] `FIREWORK_EFFECTS`
- [ ] `FIREWORK_FLIGHT_MODIFIER` bounded value? should be >= 0 javadocs ; ItemStack separate Key for exact flight duration and remove provider for Entity?
- [ ] `FIRE_DAMAGE_DELAY` bounded value? should be >= 1? javadocs; name? fireImmuneTicks
- [ ] `FIRE_TICKS` bounded value?
- [ ] `FIRST_DATE_PLAYED`
- [ ] `FIRST_TRUSTED`
- [ ] `FLUID_ITEM_STACK` impl broken , modded fluids/fluid containers?
- [ ] `FLUID_LEVEL` bounded value 1-8
- [ ] `FLUID_TANK_CONTENTS` missing provider no code usage
- [ ] `FLYING_SPEED` bounded value? should be >= 0 other entities?
- [ ] `FOOD_LEVEL` bounded value 0-20 missing provider for non-player
- [ ] `FOX_TYPE`
- [ ] `FUEL` bounded value should be >= 0
- [ ] `FUSE_DURATION` bounded value should be >= 0
- [ ] `GAME_MODE` missing provider for non-player
- [ ] `GAME_PROFILE` removal?
- [x] `GENERATION`
- [ ] `GROWTH_STAGE` bounded value lots of providers check if all are present
- [ ] `HAS_ARMS`
- [ ] `HAS_BASE_PLATE`
- [ ] `HAS_CHEST`
- [x] `HAS_EGG`
- [ ] `HAS_FISH`
- [ ] `HAS_MARKER`
- [x] `HAS_PORES_DOWN`
- [x] `HAS_PORES_EAST`
- [x] `HAS_PORES_NORTH`
- [x] `HAS_PORES_SOUTH`
- [x] `HAS_PORES_UP`
- [x] `HAS_PORES_WEST`
- [x] `HEAD_ROTATION`
- [ ] `HEALING_CRYSTAL`
- [ ] `HEALTH` bounded 0-max
- [ ] `HEALTH_SCALE` bounded value? wrong javadocs? 1-maxfloat
- [ ] `HEIGHT` readonly bounded value?
- [ ] `HELD_ITEM`
- [ ] `HIDDEN_GENE`
- [ ] `HIDE_ATTRIBUTES`
- [ ] `HIDE_CAN_DESTROY`
- [ ] `HIDE_CAN_PLACE`
- [ ] `HIDE_ENCHANTMENTS`
- [ ] `HIDE_MISCELLANEOUS`
- [ ] `HIDE_UNBREAKABLE`
- [ ] `HINGE_POSITION`
- [ ] `HOME_POSITION`
- [ ] `HORSE_COLOR` invalid impl
- [ ] `HORSE_STYLE` invalid impl
- [ ] `INFINITE_DESPAWN_DELAY`
- [ ] `INFINITE_PICKUP_DELAY`
- [ ] `INSTRUMENT`
- [ ] `INVERTED`
- [ ] `INVULNERABILITY_TICKS` bounded value should be >= 0
- [ ] `INVULNERABLE`
- [ ] `IN_WALL`
- [x] `IS_ADULT`
- [x] `IS_AFLAME`
- [x] `IS_AI_ENABLED`
- [ ] `IS_ANGRY`
- [ ] `IS_ATTACHED` lots of providers check if all are present
- [ ] `IS_BEGGING_FOR_FOOD` missing provider for cat
- [x] `IS_CELEBRATING`
- [x] `IS_CHARGED`
- [x] `IS_CHARGING_CROSSBOW`
- [x] `IS_CLIMBING`
- [x] `IS_CONNECTED_EAST`
- [x] `IS_CONNECTED_NORTH`
- [x] `IS_CONNECTED_SOUTH`
- [x] `IS_CONNECTED_UP`
- [x] `IS_CONNECTED_WEST`
- [ ] `IS_CRITICAL_HIT`
- [x] `IS_CROUCHING`
- [ ] `IS_CUSTOM_NAME_VISIBLE`
- [ ] `IS_DEFENDING` missing provider
- [ ] `IS_DISARMED`
- [ ] `IS_EATING` missing provider
- [ ] `IS_EFFECT_ONLY` missing provider
- [x] `IS_ELYTRA_FLYING`
- [ ] `IS_EXTENDED` missing provider for Piston(blockentity)?
- [x] `IS_FACEPLANTED`
- [x] `IS_FILLED`
- [x] `IS_FLAMMABLE`
- [x] `IS_FLYING`
- [x] `IS_FRIGHTENED`
- [ ] `IS_FULL_BLOCK`
- [x] `IS_GLOWING`
- [ ] `IS_GOING_HOME`
- [x] `IS_GRAVITY_AFFECTED`
- [ ] `IS_HISSING` missing provider
- [ ] `IS_IMMOBILIZED`
- [ ] `IS_INDIRECTLY_POWERED`
- [ ] `IS_INTERESTED`
- [ ] `IS_INVISIBLE`
- [ ] `IS_IN_WATER`
- [x] `IS_JOHNNY`
- [x] `IS_LAYING_EGG`
- [ ] `IS_LEADER`
- [x] `IS_LIT`
- [ ] `IS_LYING_DOWN` missing provider
- [ ] `IS_LYING_ON_BACK`
- [ ] `IS_OCCUPIED`
- [ ] `IS_ON_RAIL`
- [ ] `IS_OPEN`
- [ ] `IS_PASSABLE`
- [ ] `IS_PATROLLING`
- [x] `IS_PERSISTENT`
- [ ] `IS_PLACING_DISABLED` deduplicate IS_TAKING_DISABLED
- [x] `IS_PLAYER_CREATED`
- [ ] `IS_POUNCING` missing provider
- [ ] `IS_POWERED` lots of providers check if all providers are present
- [ ] `IS_PRIMED` missing provider
- [ ] `IS_PURRING` missing provider
- [ ] `IS_RELAXED` missing provider
- [ ] `IS_REPLACEABLE`
- [ ] `IS_ROARING`
- [ ] `IS_ROLLING_AROUND`
- [ ] `IS_SADDLED`
- [x] `IS_SCREAMING`
- [x] `IS_SHEARED`
- [x] `IS_SILENT`
- [ ] `IS_SITTING` (Fox does not extend Sittable?)
- [ ] `IS_SLEEPING` javadocs `IS_SLEEPING_IGNORED`
- [ ] `IS_SLEEPING_IGNORED` missing provider
- [ ] `IS_SMALL`
- [ ] `IS_SNEAKING`
- [ ] `IS_SNEEZING` missing provider
- [ ] `IS_SNOWY`
- [ ] `IS_SOLID`
- [ ] `IS_SPRINTING`
- [ ] `IS_STANDING`
- [ ] `IS_STUNNED`
- [ ] `IS_SURROGATE_BLOCK`
- [ ] `IS_TAKING_DISABLED` deduplicate IS_PLACING_DISABLED
- [x] `IS_TAMED`
- [ ] `IS_TRADING`
- [ ] `IS_TRAVELING`
- [ ] `IS_TRUSTING`
- [ ] `IS_UNBREAKABLE`
- [ ] `IS_UNHAPPY` missing provider
- [ ] `IS_WATERLOGGED` lots of providers check if we got all
- [ ] `IS_WET` javadocs? Most entities are wet when in water (readonly)
- [x] `ITEM_DURABILITY`
- [ ] `ITEM_STACK_SNAPSHOT`
- [ ] `KNOCKBACK_STRENGTH` bounded value should be >= 0
- [ ] `KNOWN_GENE`
- [ ] `LAST_ATTACKER`
- [ ] `LAST_COMMAND_OUTPUT`
- [ ] `LAST_DAMAGE_RECEIVED` bounded value?
- [ ] `LAST_DATE_PLAYED`
- [ ] `LAYER` bounded value
- [ ] `LEASH_HOLDER`
- [x] `LEFT_ARM_ROTATION`
- [x] `LEFT_LEG_ROTATION`
- [ ] `LIFE_TICKS`
- [ ] `LIGHT_EMISSION` provider for item/blocktype?
- [ ] `LLAMA_TYPE`  duplicate code in provider (CAT_TYPE, RABBIT_TYPE, PARROT_TYPE)
- [ ] `LOCK_TOKEN`
- [ ] `LORE`
- [ ] `MATTER_STATE`
- [ ] `MAX_AIR` bounded value should be >= 0 setter working?
- [ ] `MAX_BURN_TIME` bounded value should be > 0
- [ ] `MAX_COOK_TIME` bounded value should be > 0
- [ ] `MAX_DURABILITY`
- [ ] `MAX_FALL_DAMAGE` bounded value should be >= 0
- [ ] `MAX_HEALTH` bounded value should be > 0
- [ ] `MAX_NEARBY_ENTITIES` bounded value should be >= 0
- [ ] `MAX_SPAWN_DELAY` bounded value should be >= MIN_SPAWN_DELAY or exceptions will happen ; adjust min in impl if wrong bounds?
- [ ] `MAX_SPEED` missing provider  bounded value? not-vanilla? also for minecart? javadocs wrong?
- [ ] `MAX_STACK_SIZE` readonly bounded value?
- [ ] `MINECART_BLOCK_OFFSET`
- [ ] `MIN_SPAWN_DELAY` bounded value should be <= MAX_SPAWN_DELAY or exceptions will happen ; adjust max in impl if wrong bounds?
- [ ] `MOISTURE` bounded value 0-7
- [ ] `MOOSHROOM_TYPE` missing provider
- [ ] `MUSIC_DISK`
- [ ] `NEXT_ENTITY_TO_SPAWN`
- [ ] `NOTE_PITCH`
- [ ] `NOTIFIER` missing provider
- [ ] `OCCUPIED_DECELERATION` missing provider  bounded value? not-vanilla? also for minecart?
- [ ] `ON_GROUND`
- [ ] `PAGES`
- [ ] `PARROT_TYPE` duplicate code in provider (CAT_TYPE, RABBIT_TYPE, LLAMA_TYPE)
- [ ] `PARTICLE_EFFECT` TODOs in impl no setter?
- [ ] `PASSED_COOK_TIME` bounded value 0-MAX_COOK_TIME
- [ ] `PASSENGERS`
- [ ] `PATTERN_COLOR`
- [ ] `PHANTOM_PHASE` accessor issue with private enum
- [ ] `PICKUP_DELAY` bounded value should be >= 0
- [ ] `PICKUP_RULE`
- [ ] `PISTON_TYPE` missing provider for blockentity
- [ ] `PLACEABLE_BLOCK_TYPES`
- [ ] `PLAIN_PAGES`
- [ ] `PLUGIN`
- [ ] `PORES`
- [ ] `PORTION_TYPE`
- [ ] `POTENTIAL_MAX_SPEED` bounded value? missing provider
- [ ] `POTION_EFFECTS`
- [ ] `POTION_TYPE`
- [ ] `POWER` bounded value 0-15
- [ ] `PRIMARY_EFFECT`
- [x] `PROFESSION`
- [x] `PROFESSION_LEVEL`
- [ ] `RABBIT_TYPE`  duplicate code in provider (CAT_TYPE, PARROT_TYPE, LLAMA_TYPE)
- [ ] `RADIUS`  bounded value should be >= 0
- [ ] `RADIUS_ON_USE` bounded value? javadocs
- [ ] `RADIUS_PER_TICK` bounded value? javadocs
- [ ] `RAID_WAVE` readonly? mutable?
- [ ] `RAIL_DIRECTION`
- [ ] `REAPPLICATION_DELAY` bounded value should be >= 0
- [ ] `REDSTONE_DELAY` bounded value 1-4
- [ ] `REMAINING_AIR` bounded value 0-MAX_AIR
- [ ] `REMAINING_BREW_TIME` bounded value should be >= 0
- [ ] `REMAINING_SPAWN_DELAY` bounded value?
- [ ] `REPLENISHED_FOOD`
- [ ] `REPLENISHED_SATURATION`
- [ ] `REPRESENTED_INSTRUMENT`
- [ ] `REQUIRED_PLAYER_RANGE` bounded value should be >= 0
- [ ] `RESPAWN_LOCATIONS`
- [x] `RIGHT_ARM_ROTATION`
- [x] `RIGHT_LEG_ROTATION`
- [ ] `ROARING_TIME` bounded value? should be >= 0
- [ ] `ROTATION` missing provider for blockstate? are there any?
- [ ] `SATURATION` bounded value should be >= 0 (in vanilla upper limit = foodlevel) missing provider for non-player?
- [ ] `SCALE` readonly bounded value?
- [ ] `SECONDARY_EFFECT`
- [ ] `SECOND_TRUSTED`
- [ ] `SHOOTER` not all projectile sources supported , more projectiles?
- [ ] `SHOW_BOTTOM`
- [ ] `SIGN_LINES`
- [ ] `SIZE` bounded value (phantom 0-64) (slime should be >0 , no max?)
- [ ] `SKIN` setter for player? should this be collection instead? uuid? javadocs instructions to get a ProfileProperty
- [ ] `SKIN_MOISTURE`
- [ ] `SKY_LIGHT`
- [ ] `SLAB_PORTION`
- [ ] `SLOT_INDEX` readonly bounded value?
- [ ] `SLOT_POSITION`
- [ ] `SLOT_SIDE`
- [ ] `SLOWS_UNOCCUPIED` missing provider, boats?
- [ ] `SNEEZING_TIME` bounded value? unsure about impl
- [ ] `SPAWNABLE_ENTITIES`
- [ ] `SPAWN_COUNT` bounded value should be >= 0
- [ ] `SPAWN_RANGE` bounded value should be >= 0
- [ ] `SPECTATOR_TARGET`
- [ ] `STAIR_SHAPE`
- [ ] `STATISTICS`
- [ ] `STORED_ENCHANTMENTS`
- [ ] `STRENGTH` bounded value 1-5
- [ ] `STRUCTURE_AUTHOR`
- [ ] `STRUCTURE_IGNORE_ENTITIES`
- [ ] `STRUCTURE_INTEGRITY` bounded value 0-1 javadocs
- [ ] `STRUCTURE_MODE`
- [ ] `STRUCTURE_POSITION`
- [ ] `STRUCTURE_POWERED`
- [ ] `STRUCTURE_SEED`
- [ ] `STRUCTURE_SHOW_AIR`
- [ ] `STRUCTURE_SHOW_BOUNDING_BOX`
- [ ] `STRUCTURE_SIZE`
- [ ] `STUCK_ARROWS` bounded value should be >= 0
- [ ] `STUNNED_TIME` bounded value? should be >= 0
- [ ] `SUCCESS_COUNT` bounded value should be >= 0
- [ ] `SUSPENDED` missing provider? what is this? (smth with tripwire previously but not implemented)
- [x] `SWIFTNESS`
- [ ] `TAGS`
- [x] `TAMER`
- [ ] `TARGET_ENTITIES`
- [ ] `TARGET_ENTITY` missing provider for agents
- [ ] `TARGET_LOCATION`
  - [x] EyeOfEnder
  - [ ] Player (Kompass)
- [ ] `TARGET_POSITION`
- [ ] `TICKS_REMAINING` bounded value? sould be >= 0 setter TODO
- [x] `TOOL_TYPE`
- [ ] `TRACKS_OUTPUT`
- [x] `TRADE_OFFERS`
- [ ] `TROPICAL_FISH_SHAPE` missing provider
- [ ] `UNHAPPY_TIME` bounded value? sould be >= 0 missing provider
- [ ] `UNIQUE_ID`
- [ ] `UNOCCUPIED_DECELERATION` missing provider  bounded value? not-vanilla? (also for minecart?)
- [ ] `UNSTABLE`
- [ ] `UPDATE_GAME_PROFILE` missing provider no usage dataholder?
- [ ] `VANISH`
- [ ] `VANISH_IGNORES_COLLISION`
- [ ] `VANISH_PREVENTS_TARGETING`
- [x] `VEHICLE`
- [x] `VELOCITY`
- [x] `VILLAGER_TYPE`
- [ ] `WAIT_TIME` bounded value?
- [x] `WALKING_SPEED` 
- [x] `WILL_SHATTER`
- [x] `WIRE_ATTACHMENTS`
- [x] `WIRE_ATTACHMENT_EAST`
- [x] `WIRE_ATTACHMENT_NORTH`
- [x] `WIRE_ATTACHMENT_SOUTH`
- [x] `WIRE_ATTACHMENT_WEST`
- [ ] `WOLOLO_TARGET`
- [ ] `WOOD_TYPE` missing provider for BlockStates, modded wood?
